import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

const inter = Inter({ subsets: ["latin"] });
const roboto=Roboto({subsets:["latin"],weight:["400","700"] })
export const metadata = {
  title: "Challenge",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       
      <body className={roboto.className}>
        <Navbar    />
        {children}
        <Footer />
        </body>
    </html>
  );
}
